defaults:
  - CLIPVisionModelPool@: _template
  - /model/clip-vit@models:
      - clip-vit-base-patch32
      - clip-vit-base-patch32_svhn
      - clip-vit-base-patch32_mnist
  - /dataset/image_classification/train@train_datasets:
      - svhn
      - mnist
  - /dataset/image_classification/test@test_datasets:
      - svhn
      - mnist